In [1]:
## Python for Data Analysis - Numpy

In [2]:
## Numpy Arrays

In [3]:
my_list = [1,2,3]

In [4]:
my_list

[1, 2, 3]

In [5]:
import numpy as np

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [8]:
my_mat = [[1,2,3], [4,5,6],[7,8,9]]

In [11]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(0,11,2)    # 0부터 11미만까지 2 간격으로 출력. 

array([ 0,  2,  4,  6,  8, 10])

In [35]:
np.zeros((3))

array([0., 0., 0.])

In [21]:
np.zeros((5,5))  # 5개의 0 행, 5개의 0 열

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((3,3))   # 1로..     zeros 와  ones만 가능

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.linspace(0,5,10)   # 0부터 5까지 같은 차이값으로 떨어진 10개의 수 

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [39]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
np.random.rand(5)

array([0.10101985, 0.25630044, 0.50299495, 0.45130774, 0.63925476])

In [42]:
np.random.rand(5,2)

array([[0.51518662, 0.36397246],
       [0.66047477, 0.86760484],
       [0.71844762, 0.98009298],
       [0.85935997, 0.31861186],
       [0.72099584, 0.27309852]])

In [45]:
np.random.randn(4,5)

array([[ 0.74418626, -0.76467323,  3.29271719, -0.39248524,  0.80878448],
       [-0.06748383, -0.14206425, -2.04705061,  0.2197521 ,  0.48106637],
       [ 0.39460131,  0.6085401 , -0.4777547 , -0.30078029,  1.2954846 ],
       [-0.17751577,  1.03927286, -0.98837075,  0.6549974 , -0.14130923]])

In [50]:
np.random.randint(1,100,10)    # 1에서 100까지 숫자중 랜덤으로 출력하고 10개를 출력.

array([95, 42, 77, 64,  8, 87, 15, 32,  2, 71])

In [51]:
arr = np.arange(25)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
ranarr = np.random.randint(0, 50, 10)

In [55]:
ranarr

array([32, 30,  6, 33,  6, 10,  2, 41, 20,  7])

In [60]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
ranarr.max()

41

In [64]:
ranarr.min()

2

In [65]:
ranarr

array([32, 30,  6, 33,  6, 10,  2, 41, 20,  7])

In [66]:
ranarr.argmax()     # max 벨류(41)이 몇번째 위치에 있는지.. 

7

In [67]:
ranarr.argmin()

6

In [69]:
arr.shape

(25,)

In [70]:
arr = arr.reshape(5,5)

In [71]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [72]:
arr.shape

(5, 5)

In [73]:
arr.dtype

dtype('int32')

In [74]:
from numpy.random import randint

In [76]:
randint(2,10)    #위의 from numpy.random import randint 를 해서 원래 np.randint 인데 np 를 생략해도 가능하게됨.

9

In [77]:
import numpy as np

In [78]:
arr = np.arange(0,11)

In [79]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr[3]

3

In [84]:
arr[3:7]

array([3, 4, 5, 6])

In [85]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [90]:
print(arr[:6])
print(arr[6:])

[0 1 2 3 4 5]
[ 6  7  8  9 10]


In [92]:
arr[0:5] = 100

In [93]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [94]:
arr = np.arange(0,11)

In [95]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
slice_of_arr = arr[0:6]

In [97]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [98]:
slice_of_arr[:] = 99

In [99]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [100]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [101]:
arr_copy = arr.copy()

In [102]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [103]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [106]:
arr_copy[:] = 100

In [108]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [109]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [110]:
 arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [112]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [119]:
arr_2d[1][2]

30

In [123]:
arr_2d[1,2]

30

In [125]:
arr_2d[1][2]    # 위 방법이랑 똑같은 결과. 두가지 방법으로 가능

30

In [128]:
arr_2d[:3,1:]   # 슬라이싱으로 일정부분만 모든 행,열 출력. 

array([[10, 15],
       [25, 30],
       [40, 45]])

In [132]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [133]:
arr = np.arange(1,11)

In [134]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [136]:
bool_arr = arr > 5

In [137]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [138]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [139]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [140]:
arr[arr<3]

array([1, 2])

In [143]:
arr_2d = np.arange(50).reshape(5,10)

In [144]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [142]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [146]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [147]:
arr = np.arange(0,11)

In [148]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [149]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [150]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [151]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [152]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [153]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [154]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [159]:
arr / arr

C:\Users\hoyun\AppData\Local\Temp/ipykernel_10372/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [160]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [161]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [162]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [170]:
np.sqrt(arr)  # square root 

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [171]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [165]:
np.max(arr)

10

In [166]:
arr.max()

10

In [167]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [169]:
np.log(arr)

C:\Users\hoyun\AppData\Local\Temp/ipykernel_10372/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])